### ISSUE TITLE
Unable to Perform eval

### ISSUE THREAD

**Issue by NGUXZ** [prs-eth/DeFlow#1]
1. When I set the `mode` parameter to `eval` in the configuration file (`configs/deflow_default.yaml`), the program still runs in training mode

**Comment by Zhu-Liyuan** [comment]
Thanks for your interest. As this project was done almost two years ago, I don't remember the implementation details. 
I think you can solve the issue by looking at this line:
https://github.com/prs-eth/DeFlow/blob/c1767a96abfb830f03b86fad9cbf14c6fccb180e/configs/config.py#L38

You can contact me via my current email: liyzhu [at] stanford.edu. Thanks.
